name: manuocana
favicon: null
layout_spectrum: 0.74103
typography_spectrum: 0.74942
title: manu ocana
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cdc3b0'
    - '#52453d'
    - '#060606'
    - '#958d7c'
    - '#f5f0e7'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
