name: manuocana
favicon: null
layout_spectrum: 0.24765
typography_spectrum: 0.49068
title: manu ocana
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#06070b'
    - '#484540'
    - '#d3d8db'
    - '#7f7666'
    - '#bd5b1f'
  brandStrength: 0
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
