name: manuocana
favicon: null
layout_spectrum: 0
typography_spectrum: 0.49068
title: manu ocana
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#fbfcfc'
    - '#b9b8b3'
    - '#2b2b29'
    - '#555b3f'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
