name: manuocana
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24497
title: manu ocana
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e6e7e9'
    - '#1c1c1c'
    - '#b7b6b1'
    - '#5e5c5d'
    - '#a44740'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
