name: manuocana
favicon: null
layout_spectrum: 0.9595437990501523
typography_spectrum: 0.6197666248772293
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#011124'
    - '#fefefb'
    - '#306286'
    - '#694c2a'
    - '#b58e65'
  brandStrength: 0.6492022187449038
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
