title: manu ocana
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 1
  brandStrength: 0.5
  lightness: 1
  brandColors:
    - '#FDE9D1'
    - '#8B9D9D'
    - '#C5BCB3'
    - '#1C2826'
    - '#54707B'
  rhythmicContrast: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: manuocana
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.74942
layout_spectrum: 0
